version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db01
    ports:
      - "5412:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./Backend
    container_name: employee_backend00
    ports:
      - "3412:3412"
    env_file:
      - ./Backend/server.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/public:/app/public
    networks:
      - app-network

  frontend:
    build: ./Frontend
    container_name: employee_frontend00
    ports:
      - "8036:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
